# 数据库配置
database:
  mongodb:
    username: "Edgar"
    password: "Edgar"
    db: "IP"  # database name
    collection: "ip"  # collection to store ips from the website
    host: "127.0.0.1"
    port: "27017"

# 日志配置
log:
  mode: "console"  # 或者 file，只有设置mode为file的时候filename才生效
  level: "info" # 或者 debug, trace, warning, error
  filename: "proxy.log" # 日志文件名
  max-size: 5  # MB为单位，当文件达到这个大小之后更换另一个日志文件，

# 定时任务配置
schedule:
  interval: 10  # 以小时为单位，每interval分钟开始爬取一次ip

# 接口配置
api:
  host: "127.0.0.1"
  port: "8000"